# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: nicmarson-website
description: Nic Marson's personal site
author:
  name: Nic Marson
  email: nicholas.marson@weareinstrument.com

source:      app
destination: dist

# Grunt handles images and assets.
exclude: ['images', 'styles', 'scripts', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# Load jekyll plugins
# gems: [generate_sitemap.rb, filter_posts_and_categories, category_aware_next_generator]

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: maruku
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

pygments: true
