# Site settings
title = "Nic Marson"
baseurl = "/"
languageCode = "en-us"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  Author = "Nic Marson"
  disqusShortname = "nicmarson"

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Nic Marson"
  description = "Nic Marson is a designer and developer living in Portland, Oregon."

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.nicmarson.com"
  #  ID = "42"
  #  # Track all subdomains with "*.nicmarson.com"
  #  domain = "www.nicmarson.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Nic Marson"

  # Hero section
  [params.hero]
    enable = true
    title = "About"

  # Projects section
  [params.projects]
    enable = true
    title = "Past Projects"

    [params.projects.modal]
      site = "Site"
      client = "Client"
      date = "Date"
      category = "Tech"
      role = "Role"
      buttonText = "Close project"
